---
- hosts: all

  vars:
    my_user: "{{ ansible_user_id }}"

  tasks:
  - name: Add Docker's official GPG key
    become: true
    apt_key: id=0EBFCD88 url=https://download.docker.com/linux/ubuntu/gpg state=present

  - name: Add Docker repository
    become: true
    apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable" state=present filename="docker-ubuntu-{{ ansible_distribution_release }}"

  - name: Update reposiotories cache and install "docker-ce"
    become: true
    apt: name=docker-ce state=latest update_cache=yes

  - name: Add the current user to "docker" group
    become: true
    user: name="{{ my_user }}" groups=docker append=yes

  - name: Enable container logging into Docker host syslog file
    become: true
    template: src=./docker_daemon_conf dest=/etc/docker/daemon.json owner=root group=root mode='0600' backup=yes
    notify: restart docker

  handlers:
    - name: restart docker
      become: true
      service: name=docker state=restarted
